### ISSUE TITLE
Fetching USGS data using TEEHR v0.4 requires `bokeh`

### ISSUE THREAD

**Issue by jarq6c** [RTIInternational/teehr#289]
# Duplicate
```console
# Install teehr using pip
$ pip install teehr-0.4.0.tar.gz
```
```python
# Import teehr module into Python environment
from teehr.fetching.usgs import usgs
```

# Problem
The above results in a `ModuleNotFoundError`.
```console
Traceback (most recent call last):
  File "/home/jregina/test-teehr/main.py", line 1, in <module>
    from teehr.fetching.usgs import usgs
  File "~/test-teehr/env/lib/python3.10/site-packages/teehr/__init__.py", line 1, in <module>
    from teehr.evaluation.evaluation import Evaluation  # noqa
  File "~/test-teehr/env/lib/python3.10/site-packages/teehr/evaluation/evaluation.py", line 28, in <module>
    from teehr.visualization.dataframe_accessor import TEEHRDataFrameAccessor
  File "~/test-teehr/env/lib/python3.10/site-packages/teehr/visualization/dataframe_accessor.py", line 8, in <module>
    from bokeh.plotting import figure, save, output_file, show
ModuleNotFoundError: No module named 'bokeh'
```

# Expected
Perhaps either `bokeh` should be included in dependencies or the `fetching.usgs` module shouldn't import `bokeh`?

**Comment by mgdenno** [comment]
I think we have not used the Poetry dependency groups correctly. https://python-poetry.org/docs/managing-dependencies/

bokeh is in the `viz` group but according to the docs:
```
Dependency groups, other than the implicit main group, must only contain dependencies you need in your development process. Installing them is only possible by using Poetry.

To declare a set of dependencies, which add additional functionality to the project during runtime, use [extras](https://python-poetry.org/docs/pyproject/#extras) instead. Extras can be installed by the end user using pip.
```
If we want to bokeh to be optional it seems we need to add it to `extras` and also try/catch the import, or something.

**Comment by mgdenno** [comment]
In the latest version, v0.4.0, the Bokeh package was added to the main dependencies.  This should be resolved now.
